# Generated by Django 5.2.7 on 2025-10-14 15:30

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('area', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GistIndex(fields=['area'], name='places_neig_area_4ba715_gist')],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('path', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GistIndex(fields=['path'], name='places_rout_path_e31b90_gist')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('when', models.DateTimeField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.neighborhood')),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GistIndex(fields=['location'], name='places_even_locatio_cd9fc6_gist')],
            },
        ),
    ]
