# Generated by Django 5.2.7 on 2025-11-03 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_spatial_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='event_location_gist',
        ),
        migrations.RemoveIndex(
            model_name='neighborhood',
            name='neighborhood_area_gist',
        ),
        migrations.RemoveIndex(
            model_name='route',
            name='route_path_gist',
        ),
    ]
